# Generated by Django 3.2.6 on 2021-08-29 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210829_1113'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='posts_categories',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts_posts',
        ),
    ]
