# Generated by Django 3.2.6 on 2021-09-25 03:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_cover_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_manager_name': 'query'},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('query', django.db.models.manager.Manager()),
            ],
        ),
    ]
