# Generated by Django 3.2.6 on 2021-09-28 18:58

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210925_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'default_manager_name': 'query', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('query', django.db.models.manager.Manager()),
            ],
        ),
    ]
